### PR TITLE
Polishing and Tweaks

### PR DESCRIPTION
**Pull request by Builderdog841**
## Worldgen
- Optimzed World Generation a little through more efficent caching
- Cleaned-Up Ferrosite Pillar Code
- Groundwork Code for Ferrosite Pillar Coasts (wasn't able to find the culprit of why it isn't generating yet)
- Small Flourishing Field Vegetation Tweaks (Made Skyplane and Greatoak Trees a little less common, made dark blue flowers a bit less dominant for a more vibrant atmosphere)

## Other
- Updated Corrobonite Crystal Texture
- Reduced Leaf Pile Recipe Output from 32 to 8

---

I agree to the Contributor License Agreement (CLA).

### CODE REVIEW

**Review by bconlon1 — CHANGES_REQUESTED** [review]
egg textures need to be reverted (just writing this here as a reminder for review)

**Comment by Builderdog841** [comment]
Egg textures should already have been reverted

**Comment by bconlon1** [comment]
Oh weird I see now, not sure why the change is still showing up when it does indeed seem to not be the new textures.

**Comment by Builderdog841** [comment]
might be because I also moved the egg item texture from the materials into the miscellaneous folder without changing it in that commit, didn't revert it because I thought it'd make more sense

**Review by bconlon1 — APPROVED** [review]
lgtm

**Pull request merged**
