### PR TITLE
feat: Small Amberoot Tree foliage placer + feature

### PR DESCRIPTION
**Pull request by Zepalesque**
This pull request adds the small variation of the Amberoot tree.

---

I agree to the Contributor License Agreement (CLA).

### CODE REVIEW

**Comment by Zepalesque** [comment]
oh right I forgot to mention this pull request also removes an unused parameter from both the other foliage placers’ constructors and their codecs

**Comment by OzPayn** [comment]
Are these trees able to be generated by saplings? I have only managed to get the large ones, when I feel these ones should be the ones saplings generate primarily

**Comment by Zepalesque** [comment]
hmm, odd, I can look into that yeah
I had set it so that it’s *supposed* to be about half an half, but I may have messed something up lol

**Comment by Zepalesque** [comment]
hmm, I had also made the actual worldgen spawning rate between the two half and half as well, should that be tweaked too?

**Comment by Builderdog841** [comment]
I think the the Large Amberoots should be a lot more common in the Verdants woods while the smaller ones should be more common in the Flourishing Fields

**Comment by OzPayn** [comment]
Yeah bias towards small in non-forested areas and large in forested areas sounds good, then I'd say 2/3 of the saplings should be small and 1/3 should be large

**Comment by Zepalesque** [comment]
ok, made those tweaks and fixed the sapling

**Review by OzPayn — APPROVED** [review]
approved

**Review by bconlon1 — APPROVED** [review]
lgtm

**Pull request merged**
