### PR TITLE
fix: Amberoot Foliage Placer fixes

### PR DESCRIPTION
**Pull request by Zepalesque**
I noticed I messed up the amberoot foliage placer logic a bit so this pull request fixes that plus renames the two amberoot foliage placers for consistency with their configured features

---

I agree to the Contributor License Agreement (CLA).

### CODE REVIEW

**Comment by Builderdog841** [comment]
I've already made pr for that

**Comment by Zepalesque** [comment]
for the name consistency?

**Comment by Builderdog841** [comment]
Yeah https://github.com/The-Aether-Team/The-Aether-II/pull/259

**Comment by Zepalesque** [comment]
ah

**Comment by Builderdog841** [comment]
I'm generally doing a Foliage Placer Code refactor atm so might be good to close this for now until that gets merged and reopen it later to prevent merge issues

**Comment by Zepalesque** [comment]
heck wait
I just realized that was the intended way for the foliage placer to be :joy:
so this pr is unnecessary

**Pull request closed without merging**
