### PR TITLE
Aercloud Adjustments

### PR DESCRIPTION
**Pull request by Builderdog841**
## Aerclouds
- Made Cold Aerclouds the dominant type of Aercloud
- Made each Aercloud Type generate in larger clusters but less common

---

I agree to the Contributor License Agreement (CLA).

### CODE REVIEW

**Review by OzPayn — CHANGES_REQUESTED** [review]
Generation Height rebalancing for the coloured aerclouds seem odd, Hugo noted they don't follow the intended design so it may be worth reverting that aspect.
Larger aerclouds, more common cold aerclouds, and rarer generation overall is good for me but the vertical placement of different colours was specifically designed with flight travel in mind. I'll see if Hugo can't share the intended distribution design to ensure we get it right though

**Comment by Builderdog841** [comment]
Updated to use old Aercloud Distribution, with adjusted rarity

**Review by bconlon1 — CHANGES_REQUESTED** [review]
The error log spam caused by aerclouds generating outside their chunk bounds will have to be fixed.

**Review by bconlon1 — APPROVED** [review]
errors seem to be fixed

**Review by devilbringer — APPROVED** [review]
gucci

**Pull request merged**
