### PR TITLE
Tempest Thunderball WIP

### PR DESCRIPTION
**Pull request by darksonic300**
- Adds the Tempest's Thunderball Projectile. WIP with placeholder textures

---

I agree to the Contributor License Agreement (CLA).

### CODE REVIEW

**Comment by bconlon1** [comment]
I would prefer if this be PRed with an entity; it's probably best to save this until then. Also the projectile wouldn't necessarily have an item equivalent.

**Comment by darksonic300** [comment]
The Item was made just for consistency with rendering stuff, though an unorthodox method I thought it was the simplest to get that right.
About the entity, sure- I'll wait for Hugo's model

**Comment by bconlon1** [comment]
It's not too hard to render a projectile without an item texture, it's also not that unorthodox given Minecraft does it for projectiles like the Ender Dragon Fireball (which was used as a reference for the renderer in The Aether: Genesis).

**Comment by darksonic300** [comment]
Oh no no, I meant mine was unorthodox. It's just that it bothered me being different from Zephyr's. I'm already changing it back to how I did back in Genesis

**Pull request closed without merging**
